title: Elias A. Reyes
logo: pfpic.jpg
description: Mechanical Engineering student @ George Mason University
##  Education

### George Mason University  
**B.S. Mechanical Engineering** 
*Jan 2025 – Present*  
- RISE Scholar — Summer 2025

### Northern Virginia Community College  
**A.S. Engineering**  
*Dec 2024*  
- NOVA CORE Scholar  
- S-STEM Spring 2024 Cohort  

show_downloads: false
google_analytics:
theme: jekyll-theme-minimal

